"use client";
import { useEffect, useState } from "react";

const WalletIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h16v11H4zM4 10.5h5l2 2h2l2-2h5M7 4.5h10"/></svg>;
const NavIcon=({type}:{type:"home"|"list"|"calendar"})=> <span className={`app-nav-icon ${type}`} aria-hidden="true"/>;

function Overview({english}:{english:boolean}){return <><div className="app-month"><small>{english?"August 2026 · base scenario":"Agosto de 2026 · cenário base"}</small><b>{english?"Your month, in balance":"Seu mês, em equilíbrio"}</b></div><section className="app-balance-card healthy"><small>{english?"Available balance":"Saldo disponível"}</small><strong>R$ 12.480<sup>,00</sup></strong><span>124% {english?"of minimum balance":"do saldo mínimo"}</span><p>{english?"R$ 2,480.00 above your minimum target.":"R$ 2.480,00 acima do mínimo desejado."}</p></section><div className="app-summary-card income"><span className="summary-icon">↗</span><div><small>{english?"Received":"Recebido"}</small><b>R$ 8.750,00</b><em>{english?"R$ 4,200.00 expected":"R$ 4.200,00 a receber"}</em></div></div><div className="app-summary-card expense"><span className="summary-icon">↘</span><div><small>{english?"Still to pay":"Ainda a pagar"}</small><b>R$ 5.320,00</b><em>{english?"R$ 7,850.00 planned":"De R$ 7.850,00 previsto no mês"}</em></div></div></>}
function Flow({english}:{english:boolean}){return <><div className="app-screen-title"><b>{english?"Monthly cash flow":"Fluxo realizado no mês"}</b><small>{english?"Income and expenses already confirmed":"Receitas e despesas já realizadas"}</small></div><div className="flow-totals"><span><small>{english?"Income":"Recebidos"}</small><b>R$ 8.750</b></span><span><small>{english?"Expenses":"Despesas"}</small><b>R$ 4.180</b></span></div><div className="line-chart"><i/><i/><i/><i/><svg viewBox="0 0 260 100" preserveAspectRatio="none"><path className="chart-income" d="M0 76 C40 68 58 55 88 58 S135 24 172 34 S222 16 260 12"/><path className="chart-expense" d="M0 88 C38 85 63 74 92 78 S140 61 172 62 S218 45 260 52"/></svg></div><div className="flow-balance"><small>{english?"Realized balance":"Saldo realizado"}</small><b>R$ 4.570,00</b></div><div className="app-summary-card contribution"><span className="summary-icon">$</span><div><small>{english?"Investment potential":"Potencial de aporte"}</small><b>R$ 1.250,00</b></div></div></>}
function Planning({english}:{english:boolean}){return <><div className="app-screen-title"><b>{english?"Planning":"Planejamento"}</b><small>{english?"Family budget forecast":"Previsão do orçamento familiar"}</small></div><div className="planning-alert"><b>{english?"Protected funds":"Valores protegidos"}</b><p>{english?"R$ 1,500.00 reserved for goals this month.":"R$ 1.500,00 reservados para metas neste mês."}</p><span>{english?"View provisions":"Ver provisionamentos"}</span></div><div className="planning-toggle"><div><b>{english?"Consider pending expenses":"Considerar despesas pendentes"}</b><small>{english?"Include unpaid amounts":"Incluir valores ainda não pagos"}</small></div><i/></div><div className="planning-result"><small>{english?"Expected month-end balance":"Saldo esperado no fim do mês"}</small><strong>R$ 14.910,00</strong><p>{english?"If all expected income and expenses are realized.":"Se todas as receitas e despesas previstas forem realizadas."}</p></div></>}
function Entries({english}:{english:boolean}){const items=english?[["Market purchase","Food","− R$ 184.90"],["Design consulting","Work","+ R$ 3,200.00"],["Internet","Home","− R$ 129.90"]]:[["Compra no mercado","Alimentação","− R$ 184,90"],["Consultoria de design","Trabalho","+ R$ 3.200,00"],["Internet","Casa","− R$ 129,90"]];return <><div className="app-screen-title"><b>{english?"Entries":"Lançamentos"}</b><small>{english?"Tap an item to edit":"Toque em um item para editar"}</small></div><div className="entry-month"><span>‹</span><b>{english?"August 2026":"agosto 2026"}</b><span>›</span></div><div className="entry-filter"><b>{english?"Search and filters":"Busca e filtros"}</b><small>{english?"Refine your entries":"Refine seus lançamentos"}</small><span>⌄</span></div><div className="entry-day"><i/><div><b>{english?"Tuesday, August 04":"Terça-feira, 04 de agosto"}</b><small>3 {english?"entries":"lançamentos"}</small></div></div>{items.map(([a,b,c],i)=><div className={`entry-item ${c.includes("+")?"positive":""}`} key={a}><span>{i===1?"↗":"▤"}</span><div><b>{a}</b><small>{b}</small></div><strong>{c}</strong></div>)}</>}
const screens=[Overview,Flow,Planning,Entries];

export function ProjectVisual({english=false}:{english?:boolean}){
  const [active,setActive]=useState(0);
  useEffect(()=>{const timer=window.setInterval(()=>setActive(current=>(current+1)%screens.length),4200);return()=>window.clearInterval(timer)},[]);
  const Screen=screens[active];
  return <div className="product-visual app-real" aria-label={english?"Animated Financial Organizer interface preview":"Prévia animada da interface do Organizador Financeiro"}><div className="glow layer-back"/><div className="parallax-orb orb-one"/><div className="parallax-orb orb-two"/><div className="phone layer-phone"><header className="app-header"><span className="app-logo"><WalletIcon/></span><span className="app-identity"><small>{english?"Financial Organizer":"Organizador Financeiro"}</small><b>{english?"Hello, Carlos":"Olá, Carlos"}</b></span><span className="app-header-action">◔</span><span className="app-header-action bell">♧</span></header><div className={`app-content screen-${active}`} key={active}><Screen english={english}/></div><nav className="app-bottom-nav"><span className={active<2?"active":""}><NavIcon type="home"/><b>{english?"Home":"Início"}</b></span><span className={active===3?"active":""}><NavIcon type="list"/><b>{english?"Entries":"Lançamentos"}</b></span><span className={active===2?"active":""}><NavIcon type="calendar"/><b>{english?"Planning":"Planejamento"}</b></span></nav></div><div className="float-card projection layer-front"><small>{english?"Expected month-end balance":"Saldo esperado no fim do mês"}</small><strong>R$ 14.910,00</strong><span>↗ {english?"base scenario":"cenário base"}</span></div><div className="float-card offline layer-mid"><span className="offline-icon">✓</span><div><strong>{english?"Local cache":"Cache local"}</strong><small>{english?"Faster reads with IndexedDB":"Leituras rápidas com IndexedDB"}</small></div></div><div className="mock-controls" aria-label={english?"Choose preview screen":"Escolher tela do mockup"}>{screens.map((_,i)=><button type="button" key={i} className={i===active?"active":""} onClick={()=>setActive(i)} aria-label={`${english?"Screen":"Tela"} ${i+1}`}/>)}</div></div>
}
