import Link from "next/link";
import { ArrowUpRight, Check } from "./icons";
import { ThemeToggle } from "./theme-toggle";

const content={
  pt:{back:"Voltar ao portfólio",lang:"EN",theme:"Alternar tema",eyebrow:"Trajetória · 2018 — agora",title:<>Software, produto<br/>e <em>impacto real.</em></>,intro:"Minha carreira foi construída resolvendo problemas de produto em contextos diferentes — de projetos independentes a plataformas globais. Sempre trabalhando entre interface, domínio e infraestrutura.",highlights:"Highlights",metrics:[["8+","anos construindo produtos"],["2×","mais inscrições após o lançamento"],["Web + Mobile","experiência multiplataforma"],["Global","times e clientes internacionais"]],history:"Histórico profissional",roles:[
    {period:"Set 2022 — agora",company:"Lemon.io",role:"Senior Full-stack Engineer · Independent Contractor",summary:"Atuação em produtos de diferentes indústrias, com foco em desenvolvimento front-end, arquitetura de MVPs e evolução de plataformas web e mobile.",highlights:["Liderança técnica de MVPs do front-end ao back-end.","Integrações com Google Calendar, Zoom e OpenAI.","Produtos com IA, animações, gamificação e agendamento em tempo real.","Modernização de legados, aumento de cobertura de testes e adoção de Storybook."],stack:"React · React Native · TypeScript · Node.js · AWS · Tailwind · GraphQL"},
    {period:"Mar — Jun 2023",company:"Leads2B",role:"Full-stack Engineer",summary:"Evolução de um CRM SaaS brasileiro voltado à prospecção e gestão de leads.",highlights:["Implementação de novas jornadas a partir do design de produto.","Otimização de gargalos em fluxos críticos de prospecção.","Contribuição na migração de uma API PHP legada para microserviços Node.js."],stack:"Vue.js · Node.js · PHP · MySQL · Redis · Microservices"},
    {period:"Abr 2022 — Jan 2023",company:"RankMyAPP",role:"Full-stack Engineer",summary:"Desenvolvimento do Pulse Solution, plataforma de atendimento e gestão de avaliações de aplicativos.",highlights:["Arquitetura de gerenciamento de tickets em tempo real.","Uploads automatizados, compartilhamento e acompanhamento ao vivo.","Melhorias de performance no Redux e suporte a WebSockets.","Migração gradual de rotas legadas para microserviços."],stack:"React · TypeScript · WebSocket · Nest.js · Redis · MySQL"},
    {period:"Abr 2021 — Abr 2022",company:"DOT digital group",role:"Full-stack Engineer",summary:"Plataformas SaaS para educação corporativa, gestão de clientes e organização de conteúdo.",highlights:["Dashboards dinâmicos, relatórios avançados e novos sistemas de notificações.","Reescritas completas com arquiteturas mais eficientes.","Correção de problemas de segurança e performance, incluindo consultas N+1.","Trabalho direto com produto, design e stakeholders."],stack:"React · TypeScript · GraphQL · Apollo · Relay · Node.js"},
    {period:"2018 — 2021",company:"Projetos independentes",role:"Full-stack Developer",summary:"Produtos completos para negócios locais, da descoberta do problema ao design, desenvolvimento e deploy.",highlights:["Plataforma para associação de ciclismo com eventos, membros e pagamentos.","Integração PIX, relatórios financeiros e CMS próprio.","API GraphQL e infraestrutura com PostgreSQL e Docker.","O lançamento dobrou o número de inscrições nos eventos."],stack:"React · Next.js · TypeScript · GraphQL · PostgreSQL · Docker"}
  ],principles:"O que levo para cada projeto",principleItems:[["Visão de produto","Tecnologia só cria valor quando melhora uma decisão ou experiência real."],["Base sustentável","Arquitetura, testes e observabilidade para o produto continuar evoluindo."],["Comunicação clara","Decisões técnicas traduzidas para produto, design e negócio."],["Autonomia responsável","Capacidade de conduzir uma entrega completa sem perder colaboração e contexto."]],cta:"Vamos construir o próximo capítulo?",contact:"Iniciar uma conversa"},
  en:{back:"Back to portfolio",lang:"PT",theme:"Toggle theme",eyebrow:"Career · 2018 — now",title:<>Software, product<br/>and <em>real impact.</em></>,intro:"My career has been built around solving product problems in different contexts — from independent projects to global platforms. Always working across interface, domain, and infrastructure.",highlights:"Highlights",metrics:[["8+","years building products"],["2×","event registrations after launch"],["Web + Mobile","cross-platform experience"],["Global","international teams and clients"]],history:"Work history",roles:[
    {period:"Sep 2022 — now",company:"Lemon.io",role:"Senior Full-stack Engineer · Independent Contractor",summary:"Products across industries, focused on front-end development, MVP architecture, and the evolution of web and mobile platforms.",highlights:["Technical leadership for full-stack MVP delivery.","Integrations with Google Calendar, Zoom, and OpenAI.","AI, animation, gamification, and real-time scheduling products.","Legacy modernization, better test coverage, and Storybook adoption."],stack:"React · React Native · TypeScript · Node.js · AWS · Tailwind · GraphQL"},
    {period:"Mar — Jun 2023",company:"Leads2B",role:"Full-stack Engineer",summary:"Evolution of a Brazilian CRM SaaS for prospecting and lead management.",highlights:["New product journeys based on design specifications.","Bottleneck optimization in critical prospecting flows.","Migration from a legacy PHP API to Node.js microservices."],stack:"Vue.js · Node.js · PHP · MySQL · Redis · Microservices"},
    {period:"Apr 2022 — Jan 2023",company:"RankMyAPP",role:"Full-stack Engineer",summary:"Development of Pulse Solution, a platform for customer support and app-review management.",highlights:["Architecture for real-time ticket management.","Automated uploads, sharing, and live tracking.","Redux performance improvements and WebSocket support.","Gradual migration from legacy routes to microservices."],stack:"React · TypeScript · WebSocket · Nest.js · Redis · MySQL"},
    {period:"Apr 2021 — Apr 2022",company:"DOT digital group",role:"Full-stack Engineer",summary:"SaaS platforms for corporate education, client management, and content organization.",highlights:["Dynamic dashboards, advanced reports, and notification systems.","Full rewrites with more efficient architectures.","Security and performance fixes, including N+1 queries.","Direct collaboration with product, design, and stakeholders."],stack:"React · TypeScript · GraphQL · Apollo · Relay · Node.js"},
    {period:"2018 — 2021",company:"Independent projects",role:"Full-stack Developer",summary:"Complete products for local businesses, from discovery and design through development and deployment.",highlights:["Cycling association platform for events, members, and payments.","PIX integration, financial reports, and a custom CMS.","GraphQL API and PostgreSQL/Docker infrastructure.","The launch doubled event registrations."],stack:"React · Next.js · TypeScript · GraphQL · PostgreSQL · Docker"}
  ],principles:"What I bring to every project",principleItems:[["Product thinking","Technology creates value when it improves a real decision or experience."],["Sustainable foundations","Architecture, tests, and observability that allow products to evolve."],["Clear communication","Technical decisions translated across product, design, and business."],["Responsible autonomy","End-to-end ownership without losing collaboration or context."]],cta:"Let's build the next chapter?",contact:"Start a conversation"}
};

export function WorkHistory({locale}:{locale:"pt"|"en"}){const c=content[locale],en=locale==="en",home=en?"/en":"/";return <main className="career-page"><nav className="nav shell"><Link className="brand" href={home}><span>CH</span><i/></Link><Link className="project-back" href={home}>← {c.back}</Link><div className="nav-tools"><Link className="language-link" href={en?"/experiencia":"/en/experience"}>{c.lang}</Link><ThemeToggle label={c.theme}/></div></nav><header className="career-hero shell"><p>{c.eyebrow}</p><h1>{c.title}</h1><div><p>{c.intro}</p><span>React · TypeScript · Product engineering</span></div></header><section className="career-highlights shell"><header><span>01</span><h2>{c.highlights}</h2></header><div>{c.metrics.map(([a,b])=><article key={a}><strong>{a}</strong><p>{b}</p></article>)}</div></section><section className="career-history"><div className="shell"><header><span>02</span><h2>{c.history}</h2></header><div className="career-timeline">{c.roles.map((item,index)=><article key={item.company}><div className="career-marker"><span>{String(index+1).padStart(2,"0")}</span><i/></div><time>{item.period}</time><div className="career-role"><small>{item.company}</small><h3>{item.role}</h3><p>{item.summary}</p><ul>{item.highlights.map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="career-stack">{item.stack}</div></div></article>)}</div></div></section><section className="career-principles shell"><header><span>03</span><h2>{c.principles}</h2></header><div>{c.principleItems.map(([a,b],i)=><article key={a}><small>{String(i+1).padStart(2,"0")}</small><h3>{a}</h3><p>{b}</p></article>)}</div></section><section className="project-cta shell"><p>{c.cta}</p><Link href={`${home}#contato`}>{c.contact}<ArrowUpRight size={24}/></Link></section></main>}
